const genText = document.getElementById("gen-text")

genText.addEventListener("click", function() {
  let messages = [
"Sua amizade ilumina meus dias como o sol ilumina o céu.",
"Com você, cada momento se torna especial e cheio de alegria.",
"Se a fofura fosse uma competição, você seria a vencedora absoluta!",
"Você é a cereja no topo do bolo da minha vida.",
"A sorte sorriu para mim quando ganhei uma amiga tão incrível como você.",
"Com você, até os dias nublados ficam mais coloridos.",
"Sua presença torna os momentos simples em memórias preciosas.",
"Amizade é como chocolate: doce, viciante e sempre deixa um gostinho de quero mais.",
"Você é a razão pela qual o termo 'amiga para todas as horas' existe.",
"Nossa amizade é como um abraço quentinho em um dia frio.",
"Com você, até as segundas-feiras se tornam mais suportáveis.",
"Você é a pitada de açúcar que faltava na minha vida.",
"Amigas como você são como estrelas: sempre brilhantes e iluminando meu caminho.",
"Se a felicidade tivesse um rosto, seria o seu quando estamos juntas.",
"Você transforma cada dia comum em uma aventura extraordinária.",
"Amizade verdadeira é como uma xícara de chá: acalenta e aquece a alma.",
"Sua amizade é o ingrediente secreto que torna minha vida deliciosa.",
"Com você, até as segundas-feiras têm um toque de magia.",
"Você é a essência da fofura em forma humana.",
"Amizade é quando o coração de uma amiga bate no mesmo ritmo que o seu.",
"Se precisar de um abraço, estou a apenas uma mensagem de distância.",
"Com você, cada dia é uma jornada repleta de sorrisos e risadas.",
"Nossa amizade é um tesouro que guardo no coração.",
"Você é como um raio de sol em um dia chuvoso.",
"Ter uma amiga como você é como ganhar na loteria da vida.",
"Compartilhar risadas contigo é a receita perfeita para a felicidade.",
"Sua amizade é o presente mais precioso que já recebi.",
"Amizade é quando o coração entende a linguagem da alma.",
"Você é a confetti da minha festa da vida: colorida, divertida e essencial.",
"Com você, até as segundas-feiras têm um toque de sexta-feira.",
"Amizade é a cola que mantém os pedaços do coração unidos.",
"Sua alegria é contagiosa, e eu sou grata por cada risada compartilhada.",
"Você é a razão pela qual as pequenas coisas da vida se tornam grandes momentos.",
"Amizade é o abraço da alma, e o seu abraço é o mais acolhedor de todos.",
"Com você, até os dias cinzentos ganham cores vibrantes.",
"Ter uma amiga como você faz da vida um verdadeiro conto de fadas.",
"Sua amizade é o farol que me guia nos mares da vida.",
"Com você, até os dias mais simples se tornam extraordinários.",
"Amizade verdadeira é como um abraço que nunca acaba.",
"Você é a razão pela qual minha playlist da vida está sempre animada.",
"Compartilhar sonhos contigo é um dos maiores presentes da vida.",
"Amizade é quando o coração entre duas pessoas é reconfortante.",
"Você é a borboleta que transforma meu jardim em um lugar mágico.",
"Com você, cada dia é uma página em branco pronta para ser preenchida com histórias incríveis.",
"Amizade é como um buquê de flores: sempre bela e enche o ambiente com perfume.",
"Você é a razão pela qual a palavra 'amiga' é tão especial para mim.",
"Compartilhar segredos contigo é como confiar meu coração a um guardião dedicado.",
"Amizade é quando duas almas dançam na harmonia da cumplicidade, e a nossa dança é a mais bonita de todas.",    
"Você é mais forte do que pensa, e esta tempestade vai passar.",
"Cada dia é uma nova oportunidade para encontrar a alegria.",
"Seu sorriso ilumina o mundo, mesmo nos dias mais sombrios.",
"Lembre-se, as nuvens podem esconder o sol, mas ele sempre está lá acima.",
"Às vezes, precisamos de tempestades para apreciar o arco-íris.",
"Você é incrivelmente resiliente, e isso vai te levar longe.",
"Não se esqueça de cuidar de si mesma; você merece amor e carinho.",
"Cada desafio que enfrentamos é uma oportunidade de crescimento.",
"A vida é uma jornada, e você está no controle do seu próprio caminho.",
"Mesmo as estrelas mais brilhantes precisam da escuridão para brilhar intensamente.",
"Não deixe que as lágrimas de hoje ofusquem a esperança de amanhã.",
"Sua força interior é como uma chama que nunca se apaga.",
"Às vezes, o descanso é a coisa mais produtiva que você pode fazer.",
"Você é única, especial e tem um propósito neste mundo.",
"Não se preocupe com o que está fora do seu controle; concentre-se no que pode mudar.",
"A vida é uma dança, e mesmo os passos errados têm sua beleza.",
"Acredite na magia que está dentro de você.",
"Sua presença é um presente para o mundo; não deixe que ninguém a faça duvidar disso.",
"A cada novo amanhecer, o mundo lhe oferece uma página em branco. Escreva uma história incrível.",
"Às vezes, é preciso passar pelas nuvens para alcançar o céu azul.",
"Você é como uma flor que desabrocha mesmo nas condições mais difíceis.",
"A paciência é uma virtude, e grandes coisas estão reservadas para você.",
"As lágrimas podem regar a semente da felicidade. Confie no processo.",
"Você é capaz de superar qualquer desafio que a vida coloque em seu caminho.",
"Não tema o desconhecido; é lá que muitas descobertas maravilhosas acontecem.",
"Mesmo nas noites mais escuras, as estrelas continuam brilhando para você.",
"Seu coração é um oceano de amor e compaixão; permita-se sentir e curar.",
"Você é uma guerreira, e as batalhas que enfrenta apenas mostram sua coragem.",
"O hoje pode ser difícil, mas o amanhã trará novas oportunidades e alegrias.",
"Não há ninguém no mundo como você. Isso é o que faz você extraordinária.",
"O que te faz única é o que te faz linda. Celebramos quem você é.",
"Às vezes, a calmaria é a preparação para uma nova e incrível jornada.",
"Cada passo que você dá é uma vitória sobre as dificuldades que enfrentou.",
"Seja gentil consigo mesma; você está fazendo o seu melhor.",
"Não desista, pois você nunca sabe o quão perto está de alcançar seus sonhos.",
"Sua luz interior é mais brilhante do que qualquer escuridão ao seu redor.",
"Você é uma estrela em ascensão; permita-se brilhar no seu próprio tempo.",
"Às vezes, a jornada é mais importante do que o destino. Aprecie cada passo.",
"Sua presença é um presente para todos ao seu redor; nunca subestime seu impacto.",
"Nada é permanente, nem mesmo as tristezas que você está enfrentando agora.",
"Você é uma obra-prima em constante evolução. Confie no processo.",
"Dentro de você reside uma força imensurável. Permita-se acessá-la.",
"A vida é cheia de altos e baixos; você está crescendo com cada experiência.",
"Sua determinação é como uma chama que nunca se apaga. Continue brilhando.",
"Mesmo nas noites mais escuras, as estrelas estão lá para guiar o seu caminho.",
"A resiliência é a sua superpotência. Continue enfrentando desafios com coragem.",
"Você é mais forte do que imagina. Confie na sua capacidade de superação.",
"Seu coração é um jardim de possibilidades. Deixe florescer a esperança.",
"Cada dia é uma nova página; escreva uma história que encha seu coração de alegria.",
"Você é amada, apoiada e valiosa. Não esqueça o quão incrível você é.",
  ]
  const textEl = document.querySelector(".textMessage")
  textEl.textContent = messages[Math.floor( Math.random()*messages.length )]
})